### ISSUE TITLE
guake-project.org is down

### ISSUE THREAD

**Issue by attso** [Guake/guake-website#17]
with the following error page:
```
Error 404 Vhost unknown.

Vhost unknown.

Varnish L7 server
```

Going by archive.org, it was reporting `Error 503 Unavailable, the server is paused.` in September and has been on the current error since October.

**Comment by NetSysFire** [comment]
Site is down since at least 2022-09-20 (according to the archwiki bot that marks dead links), but unsure if it always was the same error.
I'd have liked to fix that dead link but there appears to be no alternative target.

Related: Guake/guake#2043, but http or https does not matter here, it has the same error regardless of protocol.

**Comment by ulidtko** [comment]
Hi @NetSysFire, @attso 

I'll describe the graveyard of Guake websites / domains:

 * `guake-terminal.org` — probably registered by Gabriel Falcão, the original author. NXDOMAIN currently.
 * `guake.org` — registered by Lincoln de Sousa, the maintainer that let me and Pierre @pypingou into the project. This domain is stolen, there's a ransom being asked to hand it back to Guake maintainers. 
 * `guake-project.org` — not exactly sure whose this one is, perhaps Gaetan @gsemet registered it, and didn't renew.

Perhaps this is worth documenting somewhere more permanently — but you can sort of guess most of this from the [MAINTAINERS][] file.

[MAINTAINERS]: https://github.com/Guake/guake/blob/master/MAINTAINERS

What currently seems to work is https://guake.github.io/ — it does look like GH pages rendered from this repo.

**Comment by ulidtko** [comment]
Heads up: I managed to roll out an update to https://guake.github.io/

Per this minute, that makes it the most up-to-date of Guake websites :joy: 

I'll see around if I spot outdated URLs, will update those.

**Comment by gsemet** [comment]
this should be the correct landing page. I need to update the DNS routing I guess, I still own it, but my page hosting services became way too expensive overnight (x10 on yearly price).
