### ISSUE TITLE
Correcting Weblate links for the Guake Terminal website

### ISSUE THREAD

**Issue by milotype** [Guake/guake-website#19]
Please correct the file https://github.com/Guake/guake-website/blob/master/src/jade/public/index.jade in the master branch.

**Problem:**
The _Weblate_ links in the "Can I contribute?" section don´t work correctly and the text isn´t complete because of missing end double quotes. Also, when clicking the link "support Weblate" a "Page not found" appears.

**Screenshot:**
![Can I contribute](https://github.com/Guake/guake-website/assets/43657314/bc475e59-1c76-42ec-8077-9a2a96c01bf1)

**Current source text without end quotes:**
```
                        | If you are not a developer, you can still contribute to Guake by translating
                        | or improving its translations in <a href="https://hosted.weblate.org/projects/guake/guake/>your language</a>.
                        | Guake users are welcome to <a href="https://weblate.org/donate/>support Weblate</a>
                        | in providing this service for free for OpenSource Projects.
```
**Corrected source text with end quotes:**
```
                        | If you are not a developer, you can still contribute to Guake by translating
                        | or improving its translations in <a href="https://hosted.weblate.org/projects/guake/guake/">your language</a>.
                        | Guake users are welcome to <a href="https://weblate.org/donate/">support Weblate</a>
                        | in providing this service for free for OpenSource Projects.
```

**Solution:**
Add the missing double quotes directly in the file of the master branch.
I´m not a programmer, so please check if my solution works.

**P.S.**
Due to my old Mac computer and Firefox, I´m unfortunately not able to make changes on my guake fork, nor to send pull requests :-(

**Comment by ulidtko** [comment]
Hi @milotype, you're exactly right. I'd pushed a fix that addresses this issue. Thanks for reporting.
